# Generated by Django 3.2.18 on 2023-04-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Company Name')),
                ('description', models.TextField(blank=True, verbose_name='Company Description')),
                ('city', models.CharField(max_length=64, verbose_name='Company City')),
                ('address', models.TextField(blank=True, verbose_name='Company Address')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Vacancy Name')),
                ('description', models.TextField(blank=True, verbose_name='Vacancy Description')),
                ('salary', models.FloatField(default=0, verbose_name='Vacancy Salary')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='api.company', verbose_name='Company')),
            ],
        ),
    ]
